name: Shagun Docker Workflow

on:
  workflow_dispatch:
    inputs:
      image-choice:
        description: 'Select the image you want to pull'
        required: true
        default: 'ubuntu'
        options:
          - 'python'
          - 'node'
          - 'mysql'
          - 'redis'
          - 'ubuntu'

jobs:
  pull-and-run-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull ${{ github.event.inputs.image-choice }}

      - name: Run Docker container
        run: docker run ${{ github.event.inputs.image-choice }}

