name: Shagun
on:
    workflow_dispatch:
      inputs:
        image-choice:
          description: 'From below choose the image you want to pull'
          type: choice
          default: 'python'
          options:
            - 'mysql'
            - 'warp'
            - 'node'
            - 'alpine'
            - 'redis'
jobs:
    pull-docker-image:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Step
          uses: actions/checkout@v4
        - name: Pull and run image
          run: docker run ${{github.event.inputs.image-choice}}
          
